[package]
name = "image_upload"
version = "0.1.0"
authors = ["Ivan Soloducha <ivan@soloduha.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0"
futures = "0.1"
